### PR TITLE
Added missing dependencies

### PR DESCRIPTION
**Pull request by Kaju-Bubanja**
Maybe this was working in earlier versions, but to get this repo to compile with ldmrs support I had to add these missing dependencies.

### CODE REVIEW

**Comment by Kaju-Bubanja** [comment]
Doesnt look like this repo is actively maintained so I will close it.

**Comment by michael1309** [comment]
Hi,

last couple of days were a little bit busy. Thanks again for your hints. But we have to check this against the repository. Will be done in the next couple of days.

Best regards,
Michael

**Comment by Kaju-Bubanja** [comment]
Oh ok, sorry I didn't want to hurry you. Also I will also have to make another branch with just the PR changes which make sense to put back upstream, I just continued my work in the master branch, which kinda made the PR unusable. I will try to do that soon

**Comment by rostest** [comment]
Thanks again for your request! sick_scan2 implements the ros2 driver for a couple of different lidar devices. Most lidar families have less dependancies than the LDMRS and do not require additional libraries like pcl or libsick_ldmrs. For compatibility with other lidars in existing projects, we would like to keep these dependencies. Adding additional packages for specific lidars like LDMRS can be done by option BUILD_WITH_LDMRS_SUPPORT. This way, driver installation for other lidars remains unchanged. 
Please feel free to customize LDMRS support and configuration files in your project as needed.

**Pull request closed without merging**
